refactor(file transfer): adapt new fields in ssl config
emqx/emqx-dashboard5 pull request #2762
Opened 2024-06-19 08:22 UTC by Kinplemelon

2024-06-19 08:38 UTC, emqxqa commented
[TestExecution](https://emqx.atlassian.net/browse/QA-2618)

2024-06-19 08:48 UTC, wivwiv commented on src/schemaText/schema-text-zh.json
> +      "label": "部分链"
```suggestion
"label": "部分链验证"
```

2024-06-19 08:58 UTC, wivwiv requested changes

2024-06-19 08:58 UTC, wivwiv commented on src/schemaText/schema-text-zh.json
> +      "label": "部分链"
```suggestion
      "label": "启用部分链验证"
```

2024-06-19 08:58 UTC, wivwiv commented on src/schemaText/schema-text-zh.json
> +      "label": "验证证书中的密钥用法"
```suggestion
      "label": "验证扩展密钥用法"
```

2024-06-19 08:58 UTC, wivwiv commented on src/schemaText/schema-text-zh.json
> +      "desc": "验证对等证书中的扩展密钥用法<br/>为了进行额外的对等证书验证，这里定义的值必须出现在 [rfc5280](https://www.rfc-editor.org/rfc/rfc5280#section-4.2.1.12) 中定义的对等证书的“扩展密钥用法”中。<br/>允许的值有<br/>- `clientAuth`<br/>- `serverAuth`<br/>
```suggestion
      "desc": "验证对等证书中的扩展密钥用法<br/>为了进行额外的对等证书验证，这里定义的值必须使用 [rfc5280](https://www.rfc-editor.org/rfc/rfc5280#section-4.2.1.12) 中定义的对等证书的“扩展密钥用法”。<br/>允许的值有<br/>- `clientAuth`<br/>- `serverAuth`<br/>- `codeSigning`<br/>- `emailProtection`<br/>- `timeStamping`<br/>- `ocspSigning`<br/>- 原始 OID，例如：\"OID:1.3.6.1.5.5.7.3.2\" 意味着 `id-pk 2`，相当于 `clientAuth`<br/>也支持逗号分隔的字符串来验证多个密钥用法。<br/>例如，`\"serverAuth,OID:1.3.6.1.5.5.7.3.2\"`",
```

2024-06-19 08:58 UTC, wivwiv commented on src/schemaText/schema-text-en.json
> +      "label": "Partial Chain"
```suggestion
      "label": "Enable Partial Chain Verification"
```

2024-06-19 08:58 UTC, wivwiv commented on src/schemaText/schema-text-en.json
> +      "label": "Verify Key Usage in Cert"
```suggestion
      "label": "Verify Extended Key Usage"
```

2024-06-20 09:52 UTC, ysfscream approved these changes

2024-06-20 09:52 UTC, merged